
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ftp-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
